/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      fontFamily: {
        press: ["'Press Start 2P'", "monospace"],
        vt: ["'VT323'", "monospace"],
        mono: ["'IBM Plex Mono'", "ui-monospace", "monospace"],
      },
      colors: {
        retro: {
          bg: "var(--color-retro-bg)",
          fg: "var(--color-retro-fg)",
          orange: "var(--color-retro-orange)",
          "orange-shadow": "var(--color-retro-orange-shadow)",
          outline: "var(--color-retro-outline)",
          "outline-shadow": "var(--color-retro-outline-shadow)",
          card: "var(--color-retro-card)",
          border: "var(--color-retro-border)",
          "stripe-1": "var(--color-retro-stripe-1)",
          "stripe-2": "var(--color-retro-stripe-2)",
          "stripe-3": "var(--color-retro-stripe-3)",
          "stripe-4": "var(--color-retro-stripe-4)",
          "feat-1": "var(--color-retro-feat-1)",
          "feat-2": "var(--color-retro-feat-2)",
          "feat-3": "var(--color-retro-feat-3)",
          "user-1": "var(--color-retro-user-1)",
          "user-2": "var(--color-retro-user-2)",
          "user-3": "var(--color-retro-user-3)",
          "user-4": "var(--color-retro-user-4)",
          "user-5": "var(--color-retro-user-5)",
          "user-6": "var(--color-retro-user-6)",
        },
      },
      fontSize: {
        "retro-btn": "var(--font-size-retro-btn)",
        "retro-logo": "var(--font-size-retro-logo)",
        "retro-card-title": "var(--font-size-retro-card-title)",
        "retro-label": "var(--font-size-retro-label)",
        "retro-footer": "var(--font-size-retro-footer)",
        "retro-card-body": "var(--font-size-retro-card-body)",
        "retro-nav": "var(--font-size-retro-nav)",
        "retro-body": "var(--font-size-retro-body)",
        "retro-h1": "var(--font-size-retro-h1)",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "crt-warp": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.002)", filter: "brightness(1.05)" },
          "100%": { transform: "scale(1)" },
        },
        "float-avatar": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-8px) rotate(3deg)" },
        },
        floatA: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        floatB: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-7px)" },
        },
      },
      animation: {
        blink: "blink 1s step-end infinite",
        "crt-warp": "crt-warp 6s ease-in-out infinite",
        "float-avatar": "float-avatar 3.5s ease-in-out infinite",
        "float-a": "floatA 3.4s ease-in-out infinite",
        "float-b": "floatB 4.1s ease-in-out infinite",
        "float-a-slow": "floatA 4.6s ease-in-out infinite",
        "float-b-fast": "floatB 2.9s ease-in-out infinite",
        "float-a-mid": "floatA 3.7s ease-in-out infinite",
        "float-b-mid": "floatB 3.3s ease-in-out infinite",
        "spin-slow": "spin 12s linear infinite",
      },
    },
  },
  plugins: [],
};
